global:
  language: 'English'
  preventReviewForNewCommits: false
  level: 'MAJOR'
  exclude:
    - '**/dist/**'
    - '**/vendor/**'
    - '**/coverage/**'
  collapseComment: true
  resolveOutdatedComments: true
  skipSummary: true

reviews:
  - name: 'only ts'
    path:
      - 'src/frontend/**/*.{ts,tsx}'
    settings: # 전역 설정 오버라이딩
      level: 'SUGGESTION'
      language: 'Korean'
      exclude:
        - '**/*.min.js'
        - '**/*.test.{js,ts,py}'
        - '**/node_modules/**'
        - '**/excludeFiles/**'

  - name: 'be'
    path:
      - 'src/backend/**/*.{py,go,java}'
      - 'src/backend/**/*.{js}'
    settings: # 전역 설정 오버라이딩
      level: 'CRITICAL'
      preventReviewForNewCommits: true
